export const CANDIDATE_APPLICATION_REQUEST = "CANDIDATE_APPLICATION_REQUEST";
export const CANDIDATE_APPLICATION_SUCCESS = "CANDIDATE_APPLICATION_SUCCESS";
export const CANDIDATE_APPLICATION_FAIL = "CANDIDATE_APPLICATION_FAIL";
export const CANDIDATE_APPLICATION_RESET = "CANDIDATE_APPLICATION_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
