export const SCHEDULE_INTERVIEW_REQUEST = "SCHEDULE_INTERVIEW_REQUEST";
export const SCHEDULE_INTERVIEW_SUCCESS = "SCHEDULE_INTERVIEW_SUCCESS";
export const SCHEDULE_INTERVIEW_FAIL = "SCHEDULE_INTERVIEW_FAIL";
export const SCHEDULE_INTERVIEW_RESET = "SCHEDULE_INTERVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
