export const CREATE_INTERVIEWER_REQUEST = "CREATE_INTERVIEWER_REQUEST";
export const CREATE_INTERVIEWER_SUCCESS = "CREATE_INTERVIEWER_SUCCESS";
export const CREATE_INTERVIEWER_FAIL = "CREATE_INTERVIEWER_FAIL";
export const CREATE_INTERVIEWER_RESET = "CREATE_INTERVIEWER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
