export const SCHEDULE_INTERVIEW_REQUEST = "SCHEDULE_INTERVIEW_REQUEST";
export const SCHEDULE_INTERVIEW_SUCCESS = "SCHEDULE_INTERVIEW_SUCCESS";
export const SCHEDULE_INTERVIEW_FAIL = "SCHEDULE_INTERVIEW_FAIL";
export const SCHEDULE_INTERVIEW_RESET = "SCHEDULE_INTERVIEW_RESET";

export const CANCEL_INTERVIEW_REQUEST = "CANCEL_INTERVIEW_REQUEST";
export const CANCEL_INTERVIEW_SUCCESS = "CANCEL_INTERVIEW_SUCCESS";
export const CANCEL_INTERVIEW_FAIL = "CANCEL_INTERVIEW_FAIL";

export const CREATE_INTERVIEWER_REQUEST = "CREATE_INTERVIEWER_REQUEST";
export const CREATE_INTERVIEWER_SUCCESS = "CREATE_INTERVIEWER_SUCCESS";
export const CREATE_INTERVIEWER_FAIL = "CREATE_INTERVIEWER_FAIL";
export const CREATE_INTERVIEWER_RESET = "CREATE_INTERVIEWER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
